apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"

  RabbitMq__Host: "rabbitmq"

  Jwt__Issuer: "FCG.Users.Api"
  Jwt__Audience: "FCG.Client"
  Jwt__ExpirationMinutes: "60"

  MSSQL_PID: "Developer"
  ACCEPT_EULA: "Y"

  Mongo__ConnectionString: "mongodb://mongodb-service:27017"
  Mongo__Database: "FCGCatalogHistoryDb"
  Redis__ConnectionString: "redis-service:6379"

  Aws__SqsServiceUrl: "http://localstack-service:4566"
  Aws__UserCreatedQueueUrl: "http://localstack-service:4566/000000000000/user-created-event-queue"
  Aws__PaymentProcessedQueueUrl: "http://localstack-service:4566/000000000000/payment-processed-event-queue"