apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-prometheus
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z prometheus-service 9090; do
                echo "Aguardando Prometheus..."
                sleep 3
              done
      containers:
        - name: grafana
          image: grafana/grafana:11.2.0
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fcg-secret
                  key: GrafanaAdminPassword
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: grafana-datasources-volume
              mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              subPath: datasource.yml
              readOnly: true
      volumes:
        - name: grafana-datasources-volume
          configMap:
            name: grafana-datasources