apiVersion: v1
kind: Secret
metadata:
  name: fcg-secret
type: Opaque
stringData:
  RabbitMq__Username: "guest"
  RabbitMq__Password: "guest"

  MSSQL_SA_PASSWORD: "Fcg@123456"

  Jwt__Key: "b0YJai7BQct4QKi8Xhu9FI6S83bB9hXCih17phzXEjgdFl2T2sxMZsXJiEWr8Bs5"

  UsersConnectionString: "Server=sqlserver,1433;Database=FCGUsersDb;User Id=sa;Password=Fcg@123456;TrustServerCertificate=True;"
  CatalogConnectionString: "Server=sqlserver,1433;Database=FCGCatalogsDb;User Id=sa;Password=Fcg@123456;TrustServerCertificate=True;"
  PaymentsConnectionString: "Server=sqlserver,1433;Database=FCGPaymentsDb;User Id=sa;Password=Fcg@123456;TrustServerCertificate=True;"