apiVersion: v1
kind: Secret
metadata:
  name: fcg-secret
type: Opaque
stringData:
  RabbitMq__Username: "guest"
  RabbitMq__Password: "guest"

  MSSQL_SA_PASSWORD: "Fcg@123456"

  Jwt__Key: "b0YJai7BQct4QKi8Xhu9FI6S83bB9hXCih17phzXEjgdFl2T2sxMZsXJiEWr8Bs5"

  UsersConnectionString: "Server=sqlserver,1433;Database=FCGUsersDb;User Id=sa;Password=Fcg@123456;TrustServerCertificate=True;"
  CatalogConnectionString: "Server=sqlserver,1433;Database=FCGCatalogsDb;User Id=sa;Password=Fcg@123456;TrustServerCertificate=True;"
  PaymentsConnectionString: "Server=sqlserver,1433;Database=FCGPaymentsDb;User Id=sa;Password=Fcg@123456;TrustServerCertificate=True;"
  GrafanaAdminPassword: "Grafana@123456"

  kong.yml: |
    _format_version: "3.0"

    services:
      - name: users-api
        url: http://users-service:8080
        routes:
          - name: users-register
            paths: ["/api/users"]
            methods: ["POST"]
            strip_path: false

          - name: users-admin-list
            paths: ["/api/users"]
            methods: ["GET"]
            strip_path: false
            plugins:
              - name: jwt
                config:
                  claims_to_verify: ["exp"]

          - name: users-auth-login
            paths: ["/api/auth/login"]
            methods: ["POST"]
            strip_path: false

          - name: users-auth-me
            paths: ["/api/auth/me"]
            methods: ["GET"]
            strip_path: false
            plugins:
              - name: jwt
                config:
                  claims_to_verify: ["exp"]

      - name: catalog-api
        url: http://catalog-service:8081
        routes:
          - name: catalog-read
            paths: ["/api/games"]
            methods: ["GET"]
            strip_path: false

          - name: catalog-write
            paths: ["/api/games"]
            methods: ["POST", "PUT", "DELETE"]
            strip_path: false
            plugins:
              - name: jwt
                config:
                  claims_to_verify: ["exp"]

          - name: catalog-library-read
            paths: ["/api/library"]
            methods: ["GET"]
            strip_path: false

          - name: catalog-library-history
            paths: ["~/api/library/[^/]+/history$"]
            methods: ["GET"]
            strip_path: false
            regex_priority: 100
            plugins:
              - name: jwt
                config:
                  claims_to_verify: ["exp"]

    consumers:
      - username: fcg-users-api
        jwt_secrets:
          - key: FCG.Users.Api
            algorithm: HS256
            secret: "b0YJai7BQct4QKi8Xhu9FI6S83bB9hXCih17phzXEjgdFl2T2sxMZsXJiEWr8Bs5"