apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  type: ClusterIP
  selector:
    app: sqlserver
  ports:
    - name: sqlserver
      port: 1433
      targetPort: 1433
      protocol: TCP